[package]
name = "pow_key"
version = "0.1.0"
authors = ["David Walsh"]

[dependencies]
byteorder = "1.2.7"
bytes = "0.4.10"
clap = "~2.32"
rust-crypto = "0.2.36"
rustc-serialize = "0.3.24"
uint = "0.5.0"
